---
name: deploy_images
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running job"
        required: true
        type: string

concurrency: build-images

env:
  PACKER_VERSION: 1.8.6

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.getImages.outputs.IMAGES }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Get images
        id: getImages
        run: |
          images=$(yq -r -o=json '... comments="" | .aws_images | to_entries' ./config.yml | jq -c)
          echo $images
          echo IMAGES="$images" >> $GITHUB_OUTPUT
  deploy:
    strategy:
      matrix:
        os: ${{ fromJSON(needs.setup.outputs.matrix) }}
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{env.PACKER_VERSION}}
      - name: Packer validate
        run: packer validate ./linux.pkr.hcl
        env:
          name: '${{ matrix.os.key }}'
          product: 'secure-base-image'
          owner: '${{ matrix.os.value.owner }}'
          path: '${{ matrix.os.value.path }}'
          user: '${{ matrix.os.value.user }}'
          env: 'dev'
          regions: 'us-east-1'
          region: 'us-east-1'
          iam_instance_profile: 'test-profile'
          kms_key_id: 'alias/test-kms-key'
          epic_org_arn: 'arn'
          vpc_id: 'vpc-id'
          subnet_id: 'subnet-id'
          security_profile: 'standard'
      - name: Echo IMAGES
        shell: bash
        run: |
          echo '${{ matrix.os.value.path }}'
