---
name: deploy_images
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running job"
        required: true
        type: string

concurrency: build-images

env:
  PACKER_VERSION: 1.8.6

jobs:
  deploy:
    #strategy:
     # matrix:
        #os: [ubuntu-18-standard, ubuntu-22-standard]
    runs-on: ubuntu-latest
    steps:
      - name: "Reason: ${{ github.event.inputs.reason || 'Scheduled deploy' }}"
        env:
          REASON: ${{ github.event.inputs.reason || 'Scheduled deploy' }}
        run: echo $REASON
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{env.PACKER_VERSION}}
      - name: Echo packer
        run: packer version
      - name: Get images
        shell: bash
        run: |
          config=$(cat ./config.yml)
          images=$(yq -r '.aws_images | to_entries | .[] | .key' ./config.yml)
          echo "::set-output name=images::$images"
